site_name: "Minidevice"

theme:
  name: "material"

nav:
- Home: index.md
- Documents:
    - screencap: screencap.md
    - touch: touch.md


plugins:
- search
- mkdocstrings:
    handlers:
      python:
       paths: [..] 