name: Python package

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine

    - name: Extract version from setup.py
      id: extract_version
      run: |
        version=$(python setup.py --version)
        echo "Version: $version"
        echo "RELEASE_VERSION=$version" >> $GITHUB_ENV

    - name: Build wheel
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to GitHub Releases
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ env.RELEASE_VERSION }} ./dist/*.whl --title "Release ${{ env.RELEASE_VERSION }}" --notes "Release notes here"
